## YAML Template.
---
server:
  port: 9090
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/e-booking?useSSL=false&characterEncoding=utf-8&useUnicode=true
    username: promat
    password: 8228023mts
logging:
  level:
    org:
      ss: DEBUG
ebooking:
  rememberMeKey: 80wfj23nf0g03hgjasdf98h3fljs